keys:
  - &homePc age1npt3mv7e9tuvjeh3q2w3xshnythxh9zcfe8nrytlxhu08gudx4jsa4fg56
  - &laptop age1e3nnlfgf6ruqpzezylqgmj5h06hag9mvaxx897vkcl4qqg5dd4nsfqrjax

creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *homePc
        - *laptop
